force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Ticket_price__c.field-meta.xml
<CustomField>
    <fullName>Ticket_price__c</fullName>
    <label>Ticket price</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bus_Trip__c/Bus_Trip__c.object-meta.xml
<CustomObject>
    <label>Bus Trip</label>
    <nameField>
        <label>Bus Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Trip__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Bus Trips</relationshipLabel>
    <relationshipName>Bus_Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bus_Trip__c/fields/From_location__c.field-meta.xml
<CustomField>
    <fullName>From_location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From</label>
    <referenceTo>Location_Master__c</referenceTo>
    <relationshipLabel>Bus Trips (From)</relationshipLabel>
    <relationshipName>From_location</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus_Trip__c/fields/Tickets_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Tickets_Remaining__c</fullName>
    <label>Tickets Remaining</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus_Trip__c/fields/To_location__c.field-meta.xml
<CustomField>
    <fullName>To_location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To</label>
    <referenceTo>Location_Master__c</referenceTo>
    <relationshipLabel>Bus Trips</relationshipLabel>
    <relationshipName>To_location</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus_Trip__c/fields/Trip_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Trip_Capacity__c</fullName>
    <formula>Bus__r.Total_Capacity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trip Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus_Trip__c/fields/Trip_duration__c.field-meta.xml
<CustomField>
    <fullName>Trip_duration__c</fullName>
    <label>Trip duration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus_Trip__c/fields/Trip_timing__c.field-meta.xml
<CustomField>
    <fullName>Trip_timing__c</fullName>
    <label>Trip timing</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Seat__c/Seat__c.object-meta.xml
<CustomObject>
    <label>Seat</label>
    <nameField>
        <displayFormat>S-No-{0000}</displayFormat>
        <label>Seats Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <label>Bus</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bus__c.Is_Operational__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Seats</relationshipLabel>
    <relationshipName>Seats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat__c/fields/Bus_Trip__c.field-meta.xml
<CustomField>
    <fullName>Bus_Trip__c</fullName>
    <label>Bus Trip</label>
    <referenceTo>Bus_Trip__c</referenceTo>
    <relationshipLabel>Seats</relationshipLabel>
    <relationshipName>Seats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat__c/fields/Occupied__c.field-meta.xml
<CustomField>
    <fullName>Occupied__c</fullName>
    <formula>IF(Tagged_Ticket__c = null ||  ISPICKVAL(Tagged_Ticket__r.Ticket_Status__c ,&#39;Canceled&#39;) , false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Occupied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seat__c/fields/Seat_Number__c.field-meta.xml
<CustomField>
    <fullName>Seat_Number__c</fullName>
    <label>Seat Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat__c/fields/Ticket_Price__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Price__c</fullName>
    <formula>Bus_Trip__r.Bus__r.Ticket_price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ticket Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/customLookUpController.cls
public class customLookUpController {
    @AuraEnabled
    public static List < sObject > fetchLookUpValues(String searchKeyWord, String ObjectName, String Fields) {
        String searchKey = searchKeyWord + '%';
        
        List < sObject > returnList = new List < sObject > ();
      
        // Create a Dynamic SOQL Query For Fetch Record List with LIMIT 5   
        String sQuery =  'select id, Name, '+ Fields+' from ' +ObjectName + ' where Name LIKE: searchKey order by createdDate DESC limit 5';
        List < sObject > lstOfRecords = Database.query(sQuery);
        
        for (sObject obj: lstOfRecords) {
            returnList.add(obj);
        }
        return returnList;
    }
    @AuraEnabled
    public static List<Bus_Trip__c> getBusTrips(String fromAddr, String toAddr){
      return [SELECT id, Bus__r.Name, Bus__r.Ticket_price__c, Trip_duration__c, Trip_timing__c, Tickets_Remaining__c, Trip_Capacity__c from Bus_Trip__c
       where From_location__c =: fromAddr AND To_location__c =: toAddr AND Cancelled__c = false];  
    }

    @AuraEnabled
    public static TripWrapper fetchSeatAndUserDetails(String tripInfo){
        TripWrapper wrapp = new TripWrapper();
        wrapp.userDetail.userInfo = [SELECT name from profile where id =: userInfo.getProfileId()][0].Name;
        wrapp.userDetail.userId = userInfo.getUserId();
        wrapp.seatsList = [SELECT Id, Occupied__c, Seat_Number__c, Ticket_Price__c from Seat__c WHERE Bus_Trip__c =: tripInfo ORDER BY Seat_Number__c ASC];
        return wrapp;
    }

    public class TripWrapper{
        @AuraEnabled
        public User_Details userDetail{set;get;}
        @AuraEnabled
        public List<Seat__c> seatsList{set;get;}
        public TripWrapper(){
            userDetail = new User_Details();
        }
    }
    public class User_Details{
        @AuraEnabled
        public string userInfo{set;get;}
        @AuraEnabled
        public string userId{set;get;}
    }
}